import Head from 'next/head'

import { Product, FooterBanner, HeroBanner} from '../components'
import { client } from '../lib/client';

export default function Home({ products, bannerData }) {
  return (
    <div>
      <Head>
        <title>tuto ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       {/**hero banner */}
       <HeroBanner heroBanner={bannerData.length && bannerData[0]}/>
       {/**content */}
       <div className='products-heading'>
        <h2>Best selling Keys</h2>
        <p>Kayboards of many veriations</p>
       </div>

       <div className='products-container'>
        { products?.map((product)=> product.name)}
       </div>

       {/**footer */}
       <FooterBanner/>
    </div>
  )
}

//server side props

export const getServerSideProps = async () => {
 const query = '*[_type == "product"]';
 const products = await client.fetch(query);

 const bannerQuery = '*[_type == "banner"]';
 const bannerData = await client.fetch(bannerQuery);

 return {
  props: { products, bannerData }
 }
}
